version: "3.9"
services:
  app:
    container_name: beaubox-home
    restart: always
    build:
      context: .
      target: production
      dockerfile: Dockerfile
      args:
        USERID: 0
        GROUPID: 0
    ports:
      - '3000:3000'

networks:
  default:
    name: nginx-proxy-manager_default
    external: true