version: "3"
name: beaubox-home
services:
  app:
    restart: always
    networks:
      - beaubox-home_default
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        USERID: 0
        GROUPID: 0
    ports:
      - '3000:3000'
