version: "3.9"
name: beaubox-home
services:
  app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        USERID: 0
        GROUPID: 0
    ports:
      - '3000:3000'

networks:
  default:
    name: nginx-proxy-manager_default
    external: true