version: "3"
name: beaubox-home
services:
  app:
    networks:
      - beaubox-home_default
    build:
      restart: always
      context: ./
      dockerfile: Dockerfile
      args:
        USERID: 0
        GROUPID: 0
    ports:
      - '3000:3000'
