version: "3.9"
services:
  app:
    container_name: beaubox-home
    restart: always
    build:
      context: .
      target: production
networks:
  default:
    name: nginx-proxy-manager_default
    external: true